<a href="https://colab.research.google.com/github/Gopika-C/S3-Data-Science-Lab/blob/main/EXPERIMENT1b_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1><center>Experiment 1.B</center></h1> 

Date______________________-

Aim: To perform a review of python and matrix operations using Numpy programming               


## Numpy

- Used for scientific computing
- Helps to create/ manage N-dimensional array

In [1]:
import numpy as np #importing numpy package

In [2]:
x = np.array([1,2,3,4]) #creating numpy array from list

In [3]:
print(x)

[1 2 3 4]


In [4]:
print(type(x))

<class 'numpy.ndarray'>


In [5]:
print(x.shape) #printing the dimensoin of the array

(4,)


In [6]:
y = np.array([[1,2],[3,4]])

In [7]:
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


In [8]:
z = np.array([[1+0.j,2+5.j]])  #printing thr dimension of the numpy array

In [9]:
print(z)
print(z.shape)

[[1.+0.j 2.+5.j]]
(1, 2)


In [13]:
a = np.zeros((2,3)) #creating numpy array of zeros , of dimension (2,3)

In [14]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
print(a.shape)

(2, 3)


In [16]:
b = np.ones((2,3), dtype=int) #creating numpy array of ones , of dimension (2,3) and integer type

In [17]:
print(b)

[[1 1 1]
 [1 1 1]]


In [20]:
d = np.eye(3) ## identity matrix

In [21]:
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
e = np.arange(10) ##similar to Range function

In [23]:
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
e = np.arange(12, 21)

In [25]:
print(e)

[12 13 14 15 16 17 18 19 20]


In [26]:
e = np.arange(5,20,3)

In [27]:
print(e)

[ 5  8 11 14 17]


In [28]:
f = np.linspace(1,20,7) ## It create intervals

In [29]:
print(f)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [30]:
g = np.random.random((3,4))

In [31]:
print(g)

[[0.77389945 0.41889579 0.79095188 0.60590135]
 [0.4289923  0.47402352 0.19427075 0.21382373]
 [0.43700338 0.44495142 0.29463779 0.8998207 ]]


In [32]:
h = np.random.random((3,4)) #creating a numpy array having dimension (3,4) with random elements

In [33]:
print(h.reshape(2,2,3)) #reshaping the (3,4) array to (2,2,3)

[[[0.28119474 0.98139917 0.6783976 ]
  [0.99513692 0.96243394 0.00824543]]

 [[0.10986167 0.63239262 0.90804449]
  [0.30620521 0.04740855 0.97405472]]]


In [34]:
x = np.arange(12)
print(x)
print(x[4])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
4


In [37]:
print(x[-1])

[ 8  9 10 11]


In [38]:
x.resize(3,4)

In [39]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
print(x[-1,-1])

11


In [41]:
print(x[2][3])

11


In [42]:
y = np.arange(1,26)
print(y)
print(y[:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[1 2 3]


In [43]:
print(y[10:])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [ ]:
print(y[10:15])

[11 12 13 14 15]


In [44]:
print(y[-5:])

[21 22 23 24 25]


In [45]:
print(y[3:-3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [46]:
print(y[::3])

[ 1  4  7 10 13 16 19 22 25]


In [47]:
print(y.reshape((5,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [48]:
y = y.reshape((5,5))
print(y)
print(y[:5,:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [49]:
print(y[2:-1,1:-1])

[[12 13 14]
 [17 18 19]]


In [50]:
print(y[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [ ]:
print(y[:,-1])

[ 5 10 15 20 25]


In [ ]:
print(y[::,::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [ ]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(y[1::2,1::2])

[[ 7  9]
 [17 19]]


In [ ]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a+b)
print(a-b)
print(b-a)
print(a**2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 1  4  9 16 25]


In [ ]:
print(a>3)

[False False False  True  True]


In [ ]:
a = np.arange(0,4).reshape((2,2))

In [ ]:
b = np.eye(2)

In [ ]:
print(a*b) ##Wrong

[[0. 0.]
 [0. 3.]]


In [ ]:
print(np.dot(a,b)) ##Matrix multiplication

[[0. 1.]
 [2. 3.]]


In [ ]:
x = np.arange(1,10).reshape(3,3)

In [ ]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(x.sum())

45


In [ ]:
print(x.sum(axis=0))

[12 15 18]


In [ ]:
print(x.sum(axis=1))

[ 6 15 24]


In [ ]:
x = np.arange(1,19).reshape(3,3,2)

In [ ]:
print(x.sum(axis=1))

[[ 9 12]
 [27 30]
 [45 48]]


In [ ]:
x = np.arange(1,10).reshape(3,3)

In [ ]:
print(x)
print(x.max())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [ ]:
print(x.max(axis=0))

[7 8 9]


In [ ]:
print(x.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
